import_job:
  cron: "0 * * * *"
  class: "ImportJob"
check_duplicates:
  cron: "0 10 * * *"
  class: "CheckDuplicatesJob"
import_towns_job:
  cron: "0 3 1 * *"
  class: "ImportTownsJob"
lookup_job:
  cron: "0 */3 * * *"
  class: "LookupJob"